---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
  author: ravi
spec:
  replicas: 2
  selector:
    matchLabels:
      name: voting-app-pod
      labels:
        name: voting-app
spec:
  containers:
    - name: myvoting-app
      image: dockersamples/examplevotingapp-vote
...